name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml
    - name: copy file  
      run: mkdir staging && cp target/*.jar staging/
    - uses: actions/checkout@v4
    - name: build the docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Dockerfile
        push: false
