name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven in GitHub Actions
      run: mvn clean package -DskipTests
      
    - name: Create simplified Dockerfile
      run: |
        echo 'FROM eclipse-temurin:17-jre-alpine' > Dockerfile.simple
        echo 'WORKDIR /app' >> Dockerfile.simple
        echo 'COPY target/*.jar app.jar' >> Dockerfile.simple
        echo 'EXPOSE 8080' >> Dockerfile.simple
        echo 'ENTRYPOINT ["java", "-jar", "/app/app.jar"]' >> Dockerfile.simple
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.simple
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest
